### ISSUE TITLE
Objective and Requirements v2

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#10]
These paragraphs should answer the questions: What should you project do and which are the main requirements?

**Comment by Jarlius** [comment]
Tidigare mål och krav:

> The purpose of this project is to develop a simple audio record and playback system. A
> button will be pressed and a microphone will start recording whatever sound there is, then
> the sound will play back to the user. The main must requirements for the project:
> - The ability to control the recording with buttons on the ChipKIT board.
> - Audio playback of the recording.
> - Control of when playback start, using the ChipKIT board.
> - The system must work with a microphone and speakers.
> Optional features that may be included if time allows:
> - Voice changer features, controlled through the ChipKIT board.
> - Custom recording length.
> - Display of useful information like voice changer mode, current recording time and
> last recording length.

**Comment by Jarlius** [comment]
Ska vi börja nämna att vi bytt projekt här, eller i reflektionen? I så fall blir det något såhär:

The purpose of this project was initially to record and playback sound through the ChipKit board, however, a busy autumn made us postpone acquiring the necessary equipment. When time ran out, we switched to a simple 2D game, using text symbols from the labs as graphics. Many features were achieved in the end:

- A moving "sidescroller" screen where rows of characters move to the left based on a timer.
- A player character, controlled with two buttons for moving upwards and downwards.
- Random generation of non-player characters, spreading out obstacles, powerups and treasure.
- A score counter, displayed at the end and based on distance traveled and treasure picked up.
- Hit detection, allowing player to pick up powerups and ending the game if an obstacle.
- God mode, initiated when picking up powerups and allowing the player to pass through obstacles 10 steps.
- Fade out mode, warning the player that god mode is fading by flicking between god character and player character.
- Increase in speed as time goes by, to make the game more challenging.

What we did not achieve due to lack of time but would've liked to was:

- A highscore page, stored between games and saved when the ChipKit board shuts down.
- Replacing the rows of text symbols with pixels, and creating more interesting character entities.

**Comment by simhel2** [comment]
Tycker det låter bra! ska äta frukost sen kommer jag. Tror vi kan skriva på den med att göra pixlar istället att det kanske skulle bli mer responsive och att det skulle bli en bättre illusion of movement.
Tycker vi kan skylla på att minnet på chipkittet var för litet för att få trevlig ljudkvalitét btw ! det är ju en fin ursäkt ;) att den inte nådde våra krav, inte bara att vi var kiss liksom.

**Comment by simhel2** [comment]
Fixade ihopskrivna ord som inte ska vara det 

The purpose of this project was initially to record and playback sound through the ChipKit board, however, a busy autumn made us postpone acquiring the necessary equipment. When time ran out, we switched to a simple 2D game, using text symbols from the labs as graphics. Many features were achieved in the end:

A moving "side-scroller" screen where rows of characters move to the left based on a timer.
A player character, controlled with two buttons for moving upwards and downwards.
Random generation of non-player characters, spreading out obstacles, power-ups and treasure.
A score counter, displayed at the end and based on distance traveled and treasure picked up.
Hit detection, allowing player to pick up power-ups and ending the game if an obstacle.
God mode, initiated when picking up power-ups and allowing the player to pass through obstacles 10 steps.
Fade out mode, warning the player that god mode is fading by flicking between god character and player character.
Increase in speed as time goes by, to make the game more challenging.
What we did not achieve due to lack of time but would've liked to was:

A high score page, stored between games and saved when the ChipKit board shuts down.
Replacing the rows of text symbols with pixels, and creating more interesting character entities.
