### ISSUE TITLE
Verification v2

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#12]
The verification paragraph should answer: How did you test or verify that you solution is correct?

**Comment by Jarlius** [comment]
> Three parts needs to be tested; Microphone, Memory and Speakers. The Microphone can
> be considered operational when it changes data in designated memory. Memory itself is a
> bit trickier, and will presumably be stored as an array with a currently unknown datatype.
> The Speaker is the easiest to verify, as it will play audio when it is working.

**Comment by simhel2** [comment]
We had to test all the parts of the game and how they interecated with eachother. The buttons, the random generation, the power-ups, the hit detection, the game moving faster and the start screen. 

Luckily due to the simplicity of the game most of these were simple to test and verify by playing the game, trying to first see that it works in the general case then try to achieve specific niche situations in the game. To test the niche situations we sometimes changed modifiers within the game. For instance to test the power ups we increased the likelyhood of powerups appearing to test if they interfered with eachother or themselves and to test the winnning end screen we made the game easy to complete.

**Comment by simhel2** [comment]
tog bort stavfel 

We had to test all the parts of the game and how they interacted with each other. The buttons, the random generation, the power-ups, the hit detection, the game moving faster and the start screen.

Luckily due to the simplicity of the game most of these were simple to test and verify by playing the game, trying to verify correctness in the general case then try to achieve specific niche situations in the game. To test the niche situations we sometimes changed modifiers within the game. For instance to test the power ups we increased the likelihood of power-ups appearing (to test if they interfered with each other or themselves) and to test the winning end screen we made the game easy to complete.
